name: Hadolint Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyse-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install hadolint
        run: |
          curl -sL -o hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-$(uname -s)-$(uname -m)
          chmod +x hadolint
          sudo mv hadolint /usr/local/bin/

      - name: Analyze Dockerfile with hadolint
        run: hadolint ./super_calculator/Dockerfile
