name: ReleaseWorkflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: connection Dockerhub
      uses: docker/login-action@v1
      with:  
       username: ${{secrets.username}}
       password: ${{secrets.password}}
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with: 
        context: ./super_calculator
        file: ./super_calculator/Dockerfile
        push: true
        tags: ${{secrets.username}}/project_repo

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '16'

 

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Install GoReleaser
        run: |
          curl -sL https://github.com/goreleaser/goreleaser/releases/download/v0.182.1/goreleaser_Linux_x86_64.tar.gz | tar xz
          sudo mv goreleaser /usr/local/bin/
      - name: Run GoReleaser
        run: |
          goreleaser release --snapshot --rm-dist 
        env:
          GITHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
